### PR TITLE
WIP: Add streaming server

### PR DESCRIPTION
**Pull request by luca-s**
This PR provides the data streaming functionality, but it is not ready to be merged. 

Depending on the configuration, one or more servers are spawn  as separate process (`multiprocessing.Process`), each one streaming a configurable set of cards channels (32 = 2cards x 16channels) to the connected clients. Ideally only one server is configured, which would stream all the channels, but depending on the performance it might be that we want to spawn more than one server.

The servers are separate processes, because I don't want the card reader to be affected in any way (performance or network issues) by the streaming functionality. The data is exchanged between card reader and streaming servers via IPC (`multiprocessing.Pipe`). The server itself is implemented via python asyncio, so that it should achieve high performance.

The data packets that are sent to the client use the timestaps computed by the `TimeStamps` class so that the asdf files and the streamed data are consistent. If changes are made to `TimeStamps` class then both the streamed data and the asdf files are affected.

There are still few open issues that I would like to address:

1 - I noticed that `param['Acquisition']['bytes_per_transfer'] ` controls how much data is read from the cards before being delivered to the rest of the software.  The default value is `32*1024*1024`, which is too high for real-time streaming. Ideally we should be able to send few packets of data per second, worst case one packet per second. It is possible to lower the value of `param['Acquisition']['bytes_per_transfer'] ` ? I imagine there was some research done for configuring that value, but I don't know the details.

2 - The sampling frequency of the cards is 200kHz, however are all the sensors actually able to sample data at that frequency? If not, I would like to downsample (a simple decimation) each channel to the actual sensor frequency before streaming the data. Do you think that makes sense?

3 - Regarding the card data, am I correct in saying that the samples are 16bit signed integers?

Thanks
Luca

### CODE REVIEW

**Comment by kaestli** [comment]
on (2) - there are channels (accelerometers, potentially geophones) with lower target sampling rates.

**Comment by luca-s** [comment]
> on (2) - there are channels (accelerometers, potentially geophones) with lower target sampling rates.

Good, this would improve a lot the performance. 

@all - Do you think decimation is enough or would we incur in aliasing problems if we don't perform a low pass filter before the decimation? Since the original data has a fixed sampling frequency I believe decimation is enough but I am not a signal processing expert

**Comment by luca-s** [comment]
Just to clarify my previous comment. If a sensor samples at X Hz, then we can decimate and stream the data collected by GMuG to 2X Hz. In this way the signal should be received correctly on the client side. Right?

**Comment by ThomasHaagThomas** [comment]
on (1)
yes, i tried several settings, if i remember corretly, the `append_waveforms` from pyasdf comes with some overhead per call. It was related to the compression of the data. I can have a look in my notes if you want to know it in more detail. The result was the longer the buffer, the more performance. I guess you dont compress the data, so this might not apply.
I would suggest we add some performance measure into the code, in the `card_manager.py` in the `While True:` loop one can see if it is busy processing data or waiting for the buffer to fill.

Yes, lowering the number should work. However there is a restriction, the `ram_buffer_size` needs to be divisible without remainder by the `bytes_per_transfer`. (curently: 128x1024x1024 / (32x1024x1024) = 4). This simplified the implementation, a buffer placed at the end of the RAM always fits and is never cut into two parts.

on (2)
I think this makes sense. I am not completely sure, but i would say decimation usually includes some sort of low pass filtering. e.g. decimation by 10: adding 10 samples, then dividing by 10 to get one downsampled value is a low pass filter. I used obspy.core.stream.Stream.decimate which comes with filtering.

on (3)
yes. `print(type(np_data_list[1][1][1]))` shows me `<class 'numpy.int16'>`

**Comment by luca-s** [comment]
Thanks for the info @ThomasHaagThomas. 

I will merge this PR then and I will open a new one for the optimization of `bytes_per_transfer`. 

> on (2)
> I think this makes sense. I am not completely sure, but i would say decimation usually includes some sort of low pass filtering.  e.g. decimation by 10: adding 10 samples, then dividing by 10 to get one downsampled value is a low pass filter. I used obspy.core.stream.Stream.decimate which comes with filtering.

I remember that I need to perform a low band filter at half of the dowsampled frequency to avoid aliasing. However I was wondering if it is possible to avoid the filtering step given that we know the hardware provides  data where  frequency components above a certain threshold are not present. I think it is better to discuss this aspect in person. I probably need to have a more in depth understanding of the hardware.

**Pull request merged**
